name: Sam I Am
favicon: null
layout_spectrum: 0.4978883066214621
typography_spectrum: 0.9337702116463333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8585615158081055
  lightness: 0.9318772275000811
  saturation: 0.8433992899954319
  rhythmicContrast: 0.7412102003581822
purpose: []
